apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: # Moved left to align with selector
    metadata:
      labels:
        app: nginx
    spec:
      containers: # Fixed spelling typo here
      - image: nginx
        name: nginx
